
package artifactR;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ResearcherServerService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/Project2_Researcher_WEB/ResearcherServer?wsdl")
public class ResearcherServerService
    extends Service
{

    private final static URL RESEARCHERSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESEARCHERSERVERSERVICE_EXCEPTION;
    private final static QName RESEARCHERSERVERSERVICE_QNAME = new QName("http://ws/", "ResearcherServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Project2_Researcher_WEB/ResearcherServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESEARCHERSERVERSERVICE_WSDL_LOCATION = url;
        RESEARCHERSERVERSERVICE_EXCEPTION = e;
    }

    public ResearcherServerService() {
        super(__getWsdlLocation(), RESEARCHERSERVERSERVICE_QNAME);
    }

    public ResearcherServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESEARCHERSERVERSERVICE_QNAME, features);
    }

    public ResearcherServerService(URL wsdlLocation) {
        super(wsdlLocation, RESEARCHERSERVERSERVICE_QNAME);
    }

    public ResearcherServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESEARCHERSERVERSERVICE_QNAME, features);
    }

    public ResearcherServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResearcherServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ResearcherServer
     */
    @WebEndpoint(name = "ResearcherServerPort")
    public ResearcherServer getResearcherServerPort() {
        return super.getPort(new QName("http://ws/", "ResearcherServerPort"), ResearcherServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResearcherServer
     */
    @WebEndpoint(name = "ResearcherServerPort")
    public ResearcherServer getResearcherServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "ResearcherServerPort"), ResearcherServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESEARCHERSERVERSERVICE_EXCEPTION!= null) {
            throw RESEARCHERSERVERSERVICE_EXCEPTION;
        }
        return RESEARCHERSERVERSERVICE_WSDL_LOCATION;
    }

}
