
package artifactP;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicationServer", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicationServer {


    /**
     * 
     * @return
     *     returns java.util.List<artifactP.PublicationNew>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readSortP", targetNamespace = "http://ws/", className = "artifactP.ReadSortP")
    @ResponseWrapper(localName = "readSortPResponse", targetNamespace = "http://ws/", className = "artifactP.ReadSortPResponse")
    public List<PublicationNew> readSortP();

    /**
     * 
     * @param arg0
     * @return
     *     returns artifactP.PublicationNew
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectP", targetNamespace = "http://ws/", className = "artifactP.SelectP")
    @ResponseWrapper(localName = "selectPResponse", targetNamespace = "http://ws/", className = "artifactP.SelectPResponse")
    public PublicationNew selectP(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<artifactP.PublicationNew>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readAllP", targetNamespace = "http://ws/", className = "artifactP.ReadAllP")
    @ResponseWrapper(localName = "readAllPResponse", targetNamespace = "http://ws/", className = "artifactP.ReadAllPResponse")
    public List<PublicationNew> readAllP();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<artifactP.PublicationNew>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readWantedP", targetNamespace = "http://ws/", className = "artifactP.ReadWantedP")
    @ResponseWrapper(localName = "readWantedPResponse", targetNamespace = "http://ws/", className = "artifactP.ReadWantedPResponse")
    public List<PublicationNew> readWantedP(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

}
