//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 05:13:15 PM WET 
//


package generated_sum;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}numresearchers"/>
 *         &lt;element ref="{}numcitations"/>
 *         &lt;element ref="{}topthree"/>
 *         &lt;element ref="{}interests_summary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numresearchers",
    "numcitations",
    "topthree",
    "interestsSummary"
})
@XmlRootElement(name = "catalog_summary")
public class CatalogSummary {

    @XmlElement(required = true)
    protected BigInteger numresearchers;
    @XmlElement(required = true)
    protected BigInteger numcitations;
    @XmlElement(required = true)
    protected Topthree topthree;
    @XmlElement(name = "interests_summary", required = true)
    protected InterestsSummary interestsSummary;

    /**
     * Gets the value of the numresearchers property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumresearchers() {
        return numresearchers;
    }

    /**
     * Sets the value of the numresearchers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumresearchers(BigInteger value) {
        this.numresearchers = value;
    }

    /**
     * Gets the value of the numcitations property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumcitations() {
        return numcitations;
    }

    /**
     * Sets the value of the numcitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumcitations(BigInteger value) {
        this.numcitations = value;
    }

    /**
     * Gets the value of the topthree property.
     * 
     * @return
     *     possible object is
     *     {@link Topthree }
     *     
     */
    public Topthree getTopthree() {
        return topthree;
    }

    /**
     * Sets the value of the topthree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Topthree }
     *     
     */
    public void setTopthree(Topthree value) {
        this.topthree = value;
    }

    /**
     * Gets the value of the interestsSummary property.
     * 
     * @return
     *     possible object is
     *     {@link InterestsSummary }
     *     
     */
    public InterestsSummary getInterestsSummary() {
        return interestsSummary;
    }

    /**
     * Sets the value of the interestsSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterestsSummary }
     *     
     */
    public void setInterestsSummary(InterestsSummary value) {
        this.interestsSummary = value;
    }

}
